[project]
name = "lightrag-test"
version = "0.1.0"
description = "A Streamlit-based LightRAG application for academic research."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "lightrag-hku",
    "streamlit",
    "watchdog",
    "python-pptx",
    "python-docx",
    "openpyxl",
    "pillow",
    "termcolor",
    "marker-pdf",
    "aioboto3",
    "python-dotenv",
    "ollama",
    "openai",
    "pandas",
    "numpy",
    "uv",
    "accelerate",
    "aioboto3",
    "aiohttp",
    "graspologic",
    "hnswlib",
    "nano-vectordb",
    "neo4j",
    "networkx",
    "ollama",
    "openai",
    "oracledb",
    "psycopg[binary,pool]",
    "pymilvus",
    "pymongo",
    "pymysql",
    "pyvis",
    "sqlalchemy",
    "tenacity",
    "tiktoken",
    "torch",
    "transformers",
    "xxhash",
    "pdfminer.six",
    "beautifulsoup4",
    "nest_asyncio",
    "pydantic-ai",
    "httpx",
    "pytest-asyncio",
    "stqdm",
    "fastapi",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]
