[theme]
primaryColor="#bd93f9"
backgroundColor="#282a36"
secondaryBackgroundColor="#44475a"
textColor="#f8f8f2"

[server]
fileWatcherType = "poll"
enableXsrfProtection = true
runOnSave = true

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false
showErrorDetails = false

[runner]
fastReruns = true

[global]
showWarningOnDirectExecution = false

[logger]
level = "error"
