[theme]
primaryColor="#bd93f9"
backgroundColor="#282a36"
secondaryBackgroundColor="#44475a"
textColor="#f8f8f2"

[server]
fileWatcherType = "poll"
enableXsrfProtection = true
runOnSave = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[client]
showSidebarNavigation = false
showErrorDetails = true

[runner]
fastReruns = true

[global]
showWarningOnDirectExecution = false

[logger]
level = "debug"